[package]
name = "cooptex"
version = "0.1.0"
edition = "2018"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
description = "Deadlock free Mutexes"
documentation = "https://docs.rs/cooptex"
readme = "README.md"
repository = "https://github.com/shelbyd/cooptex"
license = "MIT"
keywords = ["mutex", "deadlock", "concurrency"]

[dependencies]
loom = { version = "0.5", optional = true }

[dev-dependencies]
crossbeam = "0.8.1"
rand = "0.8.4"

[badges]
maintenance = { status = "experimental" }
