[package]
name = "cooptex"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loom = { version = "0.5", optional = true }

[dev-dependencies]
crossbeam = "0.8.1"
rand = "0.8.4"
